### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by MattHealy** [peterdemin/python-flask-replicated#2]
This package cannot be installed via the `pip` command. The `setup.py` script references a `README.rst` which exists in the Github repository, but does not exist in the PyPi archive.

```
(flask-replicated)[matthewh@folio ~]$ pip install flask-replicated
Collecting flask-replicated
  Using cached flask_replicated-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dqo6RH/flask-replicated/setup.py", line 4, in <module>
        with open('README.rst') as fp:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dqo6RH/flask-replicated/

```

Installing manually from the downloaded archive also fails:

```
(flask-replicated)[matthewh@folio ~]$ tar -zxvf flask_replicated-1.0.tar.gz 
flask_replicated-1.0/
flask_replicated-1.0/PKG-INFO
flask_replicated-1.0/setup.py
flask_replicated-1.0/flask_replicated.py
(flask-replicated)[matthewh@folio python-flask-replicated]$ cd flask_replicated-1.0/
(flask-replicated)[matthewh@folio flask_replicated-1.0]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    with open('README.rst') as fp:
IOError: [Errno 2] No such file or directory: 'README.rst'

```

Installing directly from Github works fine.

```
(flask-replicated)[matthewh@folio temp]$ pip install git+https://github.com/peterdemin/python-flask-replicated.git
Collecting git+https://github.com/peterdemin/python-flask-replicated.git
  Cloning https://github.com/peterdemin/python-flask-replicated.git to /tmp/pip-ZFO0sG-build
Installing collected packages: flask-replicated
  Running setup.py install for flask-replicated ... done
Successfully installed flask-replicated-1.0

```

**Comment by peterdemin** [comment]
I inlined README.rst into setup.py and uploaded new package (1.1) to pypi.
